# TODO: Translation updated at 2020-05-06 08:34

translate spanish strings:

    # game/options.rpy:15
    old "Light of my Life"
    new "Luz De Mi Vida"

    # game/options.rpy:32
    old "Light of my Life\"\" was created by Naughty Road\n\nLiked the game? Consider donating at {a=https://www.patreon.com/NaughtyRoad}Patreon{/a} or {a=https://www.buymeacoffee.com/NaughtyRoad}BuyMeACoffee{/a} so I can buy more assets and make more and better stuff.\n\nMusic by {a=https://www.purple-planet.com/}https://www.purple-planet.com{/a}\n\nSeveral sound effects from {a=https://freesound.org/}https://freesound.org{/a}, by Hybrid_V, freemaster2, Hitrison and others.\n\nYou are allowed to freely run, copy and distribute this game, as long as you attribute it correctly. This game is perpetually free of charge and if you paid for it, you should demand your money back.\n\nThis work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. To view a copy of this license, visit {a=https://creativecommons.org/licenses/by-nc-sa/4.0/}https://creativecommons.org/licenses/by-nc-sa/4.0/{/a}. Included copyrighted materials may have individual licensing restrictions that apply.\n\nAdditional clarification: you are free to modify the content of this game (for instance for translations, mods or extensions), and to solicit for donations for your efforts, as long as you include links to the creators website(s) as well. You are NOT allowed to charge money for this game either through direct sales, through a paywall limiting access to this game, or any other means of access that requires users to pay for access to this game.\n\nCopryright of the characters in this game are reserved by Naughty Road, but if you have a cool idea for them, just drop me a message."
    new "Luz de mi Vida fue creado por Naughty Road. ¿Te gustó el juego? Considere la posibilidad de donar en {a=https://www.patreon.com/NaughtyRoad}Patreon o {a=https://www.buymeacoffee.com/NaughtyRoad}BuyMeACoffee {a} para que pueda comprar más activos y hacer más y mejores cosas. Purple-planet.com Varios efectos de sonido de {a=https://freesound.org/}https://freesound.org, por Hybrid_V, freemaster2, Hitrison y otros. Se te permite ejecutar, copiar y distribuir libremente este juego, siempre y cuando lo atribuyas correctamente. Este juego es perpetuamente gratuito y si pagó por él, debe exigir la devolución de su dinero. Este trabajo está licenciado bajo una Licencia Internacional Creative Commons Attribution-NonCommercial-ShareAlike 4.0. Para ver una copia de esta licencia, visite {a=https://creativecommons.org/licenses/by-nc-sa/4.0/}https://creativecommons.org/licenses/by-nc-sa/4.0/{/a}. Los materiales con derechos de autor incluidos pueden tener restricciones de licencia individuales que se aplican. Aclaración adicional: eres libre de modificar el contenido de este juego (por ejemplo, para traducciones, modificaciones o extensiones), y de solicitar donaciones para tus esfuerzos, siempre que incluyas también enlaces a la(s) página(s) web de los creadores. NO se te permite cobrar dinero por este juego, ya sea a través de ventas directas, a través de un paywall que limite el acceso a este juego, o cualquier otro medio de acceso que requiera que los usuarios paguen por el acceso a este juego.\n\nLos derechos de los personajes de este juego están reservados por Naughty Road, pero si tienes una idea genial para ellos, sólo envíame un mensaje."